### ISSUE TITLE
Problem with connection to RabbitMQ 

### ISSUE THREAD

**Issue by michaldolnik** [tes/airflow-provider-rabbitmq#10]
I have a problem with the connection to RabbitMQ broker (which is run as an Amazon MQ service). 
I am using `amqps` protocol.

This is the error I am getting: 
```
[2023-01-16, 09:57:23 UTC] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/rabbitmq_provider/operators/rabbitmq.py", line 45, in execute
    hook.publish(self.exchange, self.routing_key, self.message)
  File "/home/airflow/.local/lib/python3.7/site-packages/rabbitmq_provider/hooks/rabbitmq.py", line 69, in publish
    connection = self.get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/rabbitmq_provider/hooks/rabbitmq.py", line 48, in get_conn
    conn = self.get_connection(self.rabbitmq_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
```

There is one issue with `AMQPS` protocol support, is there a problem, that it is not supported by design?

**Comment by joarobles** [comment]
AMQPS is not supported in this operator, but the underlying library pika does.

**Comment by michaldolnik** [comment]
Good, thanks
